version: '3.9'

services:
  mysql:
    image: mysql:8.0.27
    ports:
      - "33306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password